[workspace]
members = [
    "core",
    "config",
    "ecs",
    "file",
    "lib",
    "pipeline",
    "logging",
    "walker",
    "test_helper",
    "remote",
]

[workspace.metadata.workspaces]
no_individual_tags = true
