[package]
name = "xvc-workflow-tests"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "xvc"
path = "src/main.rs"

[lib]
name = "xvc_tests"
crate-type = ["rlib"]

[dependencies]
xvc-lib = { path = "../lib" }
xvc-config = { path = "../config" }
xvc-core = { path = "../core" }
xvc-logging = { path = "../logging" }
xvc-ecs = { path = "../ecs" }
xvc-file = { path = "../file" }
xvc-pipeline = { path = "../pipeline" }
xvc-walker = { path = "../walker" }
xvc-storage = { path = "../storage" }

## packages for testing
clap = {version = "^3.1", features=["derive"]}

serde = { version = "^1.0", features = ["derive"] }
serde-big-array = "^0.3"
serde_yaml = "^0.8"
serde_json = "^1.0"
crossbeam-channel = "^0.5"
subprocess = "^0.2"
log = "^0.4"
regex = "^1.5"
rand = "^0.8"

[features]
default = ["s3", "minio", "r2", "gcs", "wasabi", "digital-ocean"]
s3 = ["xvc-storage/s3"]
minio = ["xvc-storage/minio"]
r2 = ["xvc-storage/r2"]
gcs = ["xvc-storage/gcs"]
wasabi = ["xvc-storage/wasabi"]
digital-ocean = ["xvc-storage/digital-ocean"]
test-s3 = ["s3"]
test-minio = ["minio"]
test-digital-ocean=["digital-ocean"]
test-wasabi=["wasabi"]
test-gcs =["gcs"]
test-r2 = ["r2"]
test-rsync = []



[dev-dependencies]
proptest = "^1.0"
test-case = "^2.0"
xvc-test-helper = {path = "../test_helper/"}
globset = "^0.4"

shellfn = "^0.1"
jwalk = "^0.6"
